### ISSUE TITLE
Sync - 2 way?

### ISSUE THREAD

**Issue by fictitiousexistence** [doy/rbw#104]
No errors on my end just a question. 

Is sync supposed to be 2 way or download only?

There is an add command which made me thing sync should push added entries to the server. 

When I sync there is no error but the new entry does not show up on the server. 

On the github readme it states "rbw sync will .... before downloading the password database"

Thanks!

**Comment by fictitiousexistence** [comment]
@doy Thanks for the multiple profile merge btw!

Yes, when I do "RBW_PROFILE=personal rbw add testentry username --uri https://someurl"

I get a vim prompt to add the pass. Save. And then I can do "RBW_PROFILE=personal rbw get testentry" and get the password. But it does not show up on the server. 

Thanks.

**Comment by doy** [comment]
are you sure you're looking at the correct server? the way that `rbw add` works is that it posts the data to the server and then runs `rbw sync` to download the updated vault, so if `rbw get` is returning the correct data, it must be living on the server somewhere.

**Comment by fictitiousexistence** [comment]
@doy 
I was using the right server for sure. It was something on my end. No idea what. Maybe just a fluke with the search feature. I added 2 entries today and I see them on the server. 

Thanks.
