### ISSUE TITLE
feature request: Check if vault is unlocked

### ISSUE THREAD

**Issue by AdmiralNemo** [doy/rbw#12]
For automation purposes, it would be nice if there were a way to check if the vault needs to be unlocked.  Calling `rbw unlock` unconditionally is an option in some cases, it might not be in others.  If the vault is locked, the pinentry dialog will appear, blocking the script from continuing until the user either cancels it or enters the master password.

**Comment by doy** [comment]
added in 6b38682d7, thanks!
