### ISSUE TITLE
couldn't create clipboard context: XCB - couldn't establish conection: DisplayParsingError

### ISSUE THREAD

**Issue by deprecated-dot** [doy/rbw#124]
System: sway on Gentoo
rbw installation method: Gentoo ebuild in local overlay

rbw-agent worked flawlessly before recent updates (I think it was commit cf75da9), but now I just get `couldn't create clipboard context: XCB - couldn't establish conection: DisplayParsingError` in `rbw/agent.err`. 

If I uninstall and revert to a previous version with `cargo install rbw --version 1.7.1` it works again. 

I'm not sure if this is related to the fact that I'm not using X.Org or what, but I've tried installing every XCB-related lib in the Gentoo tree to get around it. Is there something I'm missing?

**Comment by doy** [comment]
fixed in #126. note that this doesn't actually implement clipboard support for wayland, since that appears to be non-trivial - if that is a thing you care about, i would be happy to look over patches (it's hard for me to do myself because i don't have any machines running wayland).
