### ISSUE TITLE
Add support for copying (T)OTP code to clipboard

### ISSUE THREAD

**Issue by rjc** [doy/rbw#127]
Hello,

`get` command received support for `--clipboard` option recently - could the same be done to `code` command, please?

While we're at it, it has taken me a while to figure out that `code` means `(t)otp`. Could the name be changed to one of the latter, with `code` remaining an alias (at least for the time being). please? I don't recal ever seeing `code` used in this context in any other application - it is usually either `totp` or `otp`.

Regards,

rjc

**Comment by Lillecarl** [comment]
Just pipe to whatever clipboard mangager you're using

```rbw get SECRET | wl-copy -n```. 

It's out of scope to handle all copy variants (pbcopy, clip.exe, wl-copy, xcopy)

**Comment by rjc** [comment]
@Lillecarl, `get` command already _has_ `--clipboard` option. `code`, on the other hand, does not, and it would be useful for it to have one, since `get` already has it, as both commands' output is usually copy-pasted somewhere.

**Comment by doy** [comment]
fixed in 1.10.0, thanks!
