### ISSUE TITLE
feature request: Change password non-interactively

### ISSUE THREAD

**Issue by AdmiralNemo** [doy/rbw#13]
As far as I can tell, the only way to change a password for an existing item in the vault is to launch a text editor.  It would be useful if there were a way to, e.g. read a new password from standard input.

**Comment by doy** [comment]
`EDITOR=tee rbw edit foo` already handles this case, i think? is there something in particular you want beyond this?

**Comment by albakham** [comment]
Maybe something like `rbw edit --interactive|-i foobar`?

**Comment by AdmiralNemo** [comment]
> `EDITOR=tee rbw edit foo` already handles this case, i think? is there something in particular you want beyond this?

I suppose that does technically work, but it would be nice for it to be a native feature.  I don't believe `tee` is available on all platforms, like Windows, for example.

**Comment by doy** [comment]
fixed in #138
