### ISSUE TITLE
Feature Request: CICD

### ISSUE THREAD

**Issue by jakeswenson** [doy/rbw#15]
I'd like to help add automated build and "deployment" support to rbw if there is interest in getting that contribution.

I'd like to suggest the following process:
1. Project Maintainer @doy would initiate a new release using [`cargo release`](https://github.com/sunng87/cargo-release)
1.1. this results in a new tagged version being created (1.0, 1.1, 1.2, etc.)
2. Using GitHub actions a build for that tag is run.
2.1. This creates a GitHub release
2.2. Then a matrix build is run for every platform that needs to be supported (linux, mac, etc)
3. Each build uploads its artifacts to the GitHub release in 2.1.

I have an example of this in place already for [my otpcli tool](https://github.com/jakeswenson/otpcli) that we could use as a starting point if that makes sense @doy?

**Comment by doy** [comment]
i would like to get ci of some sort set up for running tests, but i already have a release process that i'm happy with.

**Comment by fugkco** [comment]
@doy what's your current release process? Would you be opposed to uploading the binaries to GitHub releases? One thing that i don't like is that I have to build rbw if I want to upgrade it, I'd much prefer downloading a binary.

**Comment by doy** [comment]
i currently publish binary packages for arch linux and debian/ubuntu, as described at https://github.com/doy/rbw#installation . is there something else you would like?
