### ISSUE TITLE
"email" config option is case sensitive.

### ISSUE THREAD

**Issue by Rosuavio** [doy/rbw#158]
When trying to log in with rbw to my account on vault.bitwarden.com, if the email I give rbw does not match the one for my bitwarden account, including the casing of alphabetic characters, then when I try to log in my password does not work and I get...
```console
rbw list: failed to log in to bitwarden instance: Username or password is incorrect. Try again.
```
Once I changed the casing of the email I provided rbw to match my bitwarden account everything worked.

Most services do not care about casing of emails in any context, and I have no trouble logging into https://vault.bitwarden.com/ threw the browser using a version of my email that does not match the casing of the email bitwarden shows that they have stored.

Maybe to fallow the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), rbw should be case insensitive in the email field.

**Comment by doy** [comment]
fixed in 1.10.0, thanks!
