### ISSUE TITLE
Feature Request: Keychain Master Password storage for a streamlined password experience

### ISSUE THREAD

**Issue by jakeswenson** [doy/rbw#16]
There is a cross-platform rust crate called [`keyring`](https://crates.io/crates/keyring) that uses the running platforms secure password storage mechanism to store and access passwords. I'd love to add support for this in rbw. We can make it an optional feature, that you can opt in to with `rbw config`. 

I have an initial pass at cutting it in [in a branch](https://github.com/jakeswenson/rbw/tree/keyring-password-support).

**Comment by doy** [comment]
how would this work? just by storing the bitwarden master password in the system keychain? happy to look at pull requests regardless.

**Comment by arcnmx** [comment]
FWIW I'm looking for similar functionality, and coming from `pass` I'm taking the approach of using gpg to supply the password: https://github.com/doy/rbw/compare/master...arcnmx:master

(also at that point the agent itself seems unnecessary, I'm mostly just looking for a workflow roughly equivalent to official bw cli except not bad)

**Comment by nikaro** [comment]
@jakeswenson would you mind rebase your work and submit a PR? Or @doy taking over it?

I took a look at it, but i don't know Rust... so this is out of my reach.

**Comment by doy** [comment]
fixed in #122
