### ISSUE TITLE
Feature Request: TOTP support

### ISSUE THREAD

**Issue by jakeswenson** [doy/rbw#17]
Adding TOTP support could be nice in two cases:
1. When logging when 2fa is enabled on the account.
2. The ability to generate a TOTP code from a secret in bitwarden. this might be a new command like `rbw code <name> [<user>]`

I have a rust crate that could be used as a starting point for both — [`otpcli`](https://github.com/jakeswenson/otpcli) — but there are many others as well.

**Comment by doy** [comment]
i was already in the process of implementing this when you filed this ticket(:

**Comment by jakeswenson** [comment]
Wouldn't it be a good idea to keep the request open until its done?
Are you building it from scratch or reusing open-source crates?

**Comment by jakeswenson** [comment]
My bad! You added it already! awesome! thanks!

I will open another request for auto 2fa support

**Comment by nikaro** [comment]
When do you plan to release a version with this feature?

**Comment by doy** [comment]
oh, sorry, i didn't realize i forgot to actually make a release - i'll do that tonight

**Comment by nikaro** [comment]
I was beginning to think that you had given up on this project :sweat_smile: Thank you!
