### ISSUE TITLE
Feature request: keep vault open indefinitely

### ISSUE THREAD

**Issue by xusiai** [doy/rbw#176]
This is perhaps an unpopular feature but Bitwarden's browser addon has an option to keep the vault open indefinitely. I would appreciate this feature in rbw. I am aware it is insecure but it should be up to the user to decide whether the risk is worth it and there are use cases for me where that is the case e.g. at-home desktop machine with LUKS enabled.

**Comment by dezeroku** [comment]
I'm not sure if special handling is needed here.

That may not be the cleanest approach, but max value for the `lock_timeout` is `2^64 - 1` and its equivalent of ~ `584 * 10^9` years., so there's a lot of headroom.

So you should be able to just set it to a big value, e.g. to lock the vault after ten years you'd use `lock_timeout: 315360000`

**Comment by xusiai** [comment]
> That may not be the cleanest approach, but max value for the `lock_timeout` is `2^64 - 1` and its equivalent of ~ `584 * 10^9` years., so there's a lot of headroom.

The vault would still be locked after a reboot/shutdown which defeats the purpose for me. I do not want to have to unlock the vault after starting the computer.

**Comment by doy** [comment]
this is not a feature i am interested in supporting within rbw itself (beyond the existing functionality of setting `lock_timeout` to a high value), but you can likely get the user experience you want by using something like https://github.com/doy/rbw/blob/main/bin/rbw-pinentry-keyring to read your master password from your system keyring - this would mean you wouldn't have to enter any passwords other than whatever is necessary to unlock your keyring.
