### ISSUE TITLE
[question] usage in skripting for AWX Ansible?

### ISSUE THREAD

**Issue by gsg-git** [doy/rbw#199]
Hello!

Your tool is yeally nice to use in comparison to the bitwarden cli

Id like to use this with a skrip for awx beacuase i have a project where i mass change the passwords of certain users and likke to add them in bitwarden too.
Is this possible with rbw?

It would be very nice, because im at it with the bw cli via the support as paying customer for about a month, but no success.
with each mail i get from them, my feel this guy has no idea what hes talking about all the time...("You need to check your syntax" I SENT YOU THE COMMAND - WHY CANT YOU CORRECT IT THEN !$%&"§).

Thank you in davance!

**Comment by doy** [comment]
yes, you should be able to do this via `rbw add`/`rbw edit`/`rbw generate`. i can't help with the ansible part specifically since i've never used it, but do let me know if the documentation for those commands isn't sufficient.
