### ISSUE TITLE
rbw in script pass passowrd

### ISSUE THREAD

**Issue by omer-al-ba** [doy/rbw#201]
Hey,

First of all, great project and excellent handling of the different accounts!

I would like to use it in a script where multiple users can log in and fetch their passwords. However, after adding a new user to the config, I have to wait for the prompted display to enter the user password.

I’ve tried using the following commands to automate it:

-     echo 'password' | rbw unlock
-     echo 'password' | xargs rbw unlock

Can you please help me with this?

**Comment by yusufaktepe** [comment]
See https://github.com/doy/rbw/issues/65#issuecomment-991394623

**Comment by omer-al-ba** [comment]
@yusufaktepe i will give it a try.
Thanks for reply and i learn somethin new!
