### ISSUE TITLE
does this support parallel execution with the same session?

### ISSUE THREAD

**Issue by simonLeary42** [doy/rbw#203]
The official bitwarden CLI has a race condition on its cache file (session specific), and if you try to run it in parallel, the file will be corrupted. Does `rbw` have that problem?

I see that https://github.com/doy/rbw/commit/d4453cb44a10f9bb558fd2a5561cc5223ba36a23 added support for parallel execution on different sessions. But what about the same session?

**Comment by doy** [comment]
yes, parallel execution should work fine - the `rbw` binary will spawn a persistent agent process the first time it is run, which will be used by all further executions. that agent process mediates all access to the cache, etc., and uses mutexes internally to avoid requests from multiple clients from interfering with each other.
