### ISSUE TITLE
rbw login: incompatible protocol versions: client (1012001), agent (1009000)

### ISSUE THREAD

**Issue by mr-biz** [doy/rbw#209]
Hi,
I just tried installing and ran directly into problems.  Any and all help appreciated!
Thanks in advance!

OS / Environment: Ubuntu 24.04 running on Proxmox LXC.

Steps taken:
`    1  wget https://git.tozt.net/rbw/releases/deb/rbw_1.9.0_amd64.deb`
`    2  wget https://git.tozt.net/rbw/releases/deb/rbw_1.9.0_amd64.deb.minisig`
`    3  apt install ./rbw_1.9.0_amd64.deb`
`    4  wget https://github.com/doy/rbw/releases/download/1.12.1/rbw_1.12.1_linux_amd64.tar.gz`
`    5  tar -xzvf rbw_1.12.1_linux_amd64.tar.gz`
`    6  sudo mv rbw /usr/local/bin/`
`    7  sudo chmod +x /usr/local/bin/rbw`
`    8  rbw --version`
`    9  rbw config set email a-user@gmail.com`
`   10  rbw login`
`        rbw login: incompatible protocol versions: client (1012001), agent (1009000)`

**Comment by sedlund** [comment]
incompatible protocol versions: client (1012001), agent (1009000)

You are still running the old agent


Run

rbw stop-agent

**Comment by mr-biz** [comment]
Thanks, tried it but did not work.
 `  23  rbw stop-agent`
  ` 24  rbw purge`
 `  25  rbw login`
 `        rbw login: incompatible protocol versions: client (1012001), agent (1009000)`

**Comment by sedlund** [comment]
you still have the old one installed 

apt remove rbw

**Comment by mr-biz** [comment]
` 27  apt remove rbw`
 `  28  rbw login`
      ` rbw login: failed to run rbw-agent: No such file or directory (os error 2)`

**Comment by sedlund** [comment]
> 6 sudo mv rbw /usr/local/bin/

You only copied the client and not the agent to the path

**Comment by mr-biz** [comment]
`sudo mv rbw-agent /usr/local/bin/`

All good now, thank you!

**Comment by doy** [comment]
yup, you need to install both the `rbw` and `rbw-agent` binaries in order for things to work.
