### ISSUE TITLE
Clipboard does not work

### ISSUE THREAD

**Issue by hinricht** [doy/rbw#214]
I'd like to use `rbw get --clipboard <PW>` to copy a password to the clipboard, but it doesn't work for me.  
Nothing is copied into to clipboard.

I'm using Manjaro sway edition (wayland) and habe the `wl-copy` cmd installed.

**Comment by doy** [comment]
i believe this should be fixed in #192 - can you try version 1.13.0 and let me know if it works?

**Comment by varac** [comment]
Thanks for fixing! I'll try once 1.13.0 arrives as arch package
