### ISSUE TITLE
another release after rust 1.82 update

### ISSUE THREAD

**Issue by happysalada** [doy/rbw#217]
hi, the latest release is currently broken with rust 1.82 (doesn't compile).
If you have a moment to make another release compiling with rust 1.82 that would be amazing.
For context I'm posting this because rbw is currently broken on nixpkgs.
Thank you for making this, and no worries if you don't have time.

**Comment by sedlund** [comment]
can you post the hydra build that is broke?  It seems green to me:

https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.rbw.x86_64-linux
