### ISSUE TITLE
Error when tried to sync and login

### ISSUE THREAD

**Issue by latipun7** [doy/rbw#218]
rbw version 1.21.1

I tried to sync rbw with `rbw sync` but unsuccessful, got an error like in this issue #32. Then I tried to purge and relogin, but got an error when login.

```shell
❯ rbw login
rbw login: failed to log in to bitwarden instance: api request returned error: 429
```

Please help. Thank you.

**Comment by omentic** [comment]
I am also getting this error. I switched to Bitwarden recently and only installed `rbw` yesterday, so thought I was just holding it wrong... `rbw register` seems to succeed, but `rbw login` fails.

**Comment by tmeijn** [comment]
Getting the same error: needed to re-install laptop so need to login again using `rbw`. Seems like something has been broken by a Bitwarden change.

I tried to generate debug logs like [here](https://github.com/doy/rbw/issues/32#issuecomment-1083510075), but could not get it to work and there is no developer documentation that I could find.

`rbw register` indeed does seem to work, although it does not give any output at all, just a zero exit code.

**Comment by pcrockett** [comment]
Not sure if it's related, but I'm also seeing this in `~/.loca/share/rbw/agent.err` after running `rbw unlock`:

```
** (pinentry-gtk:14554): WARNING **: 20:11:14.144: it took 104 tries to grab the keyboard
[90m[[0m2024-12-02T19:11:25Z [33mWARN [0m rbw::api[90m][0m failed to parse JSON: 
```

I find the "failed to parse JSON" part there interesting. No idea if it's relevant. Sadly, the error message stops right there.

**Comment by pcrockett** [comment]
Looks like this might fix it: https://github.com/doy/rbw/pull/219

**Comment by tmeijn** [comment]
Can confirm that for me the build of that PR solves the issue! 🚀

**Comment by davla** [comment]
I tried again just now and it no longer seems to work. Can anyone else confirm?

**Comment by furstblumier** [comment]
Facing the same issue with the current build from main. Neither login nor register works

**Comment by Anachron** [comment]
Whenever I try to login it tells me Invalid username or password. 

However the latest beta client on Android does let me login with these exact credentials.

I use a selfhosted vaultwarden instance.

**Comment by davla** [comment]
> I tried again just now with the build from #219 and it no longer seems to work. Can anyone else confirm?

It turns out that the PR build does indeed work. I just forgot to set `RBW_AGENT` to the locally built binary.

**Comment by ymatsiuk** [comment]
Would be great if it was possible to set headers outside of the code. Imagine there was a variable `BW_API_HEADERS` (could be a configuration entry) that would allow us to set arbitrary headers in `key0=value0,key1=value1` format. In this case we don't have to change the code every time BW introduces a change or a mandatory header. The code would look much simpler just iterating over a comma separated list and appending those as headers :thinking:

**Comment by adrianschlatter** [comment]
Yup, I also ran into this problem. `brw register` seems to work, `brw login` fails with 429. I installed the official bw client on the same machine => no 429 problem. @davla: I'd offer to test #219, too, but I run into a problem. I'm a newby regarding rust/cargo so maybe I'm just doing an obvious mistake that you could help me correct? 🙏 

```
git clone git@github.com:doy/rbw.git
cd rbw
git fetch origin pull/219/head:pr219
git checkout pr219
cargo install --locked -Znext-lockfile-bump --path .
```

I get

```
» cargo install --locked -Znext-lockfile-bump --path rbw
  Installing rbw v1.12.1 (/home/adrian/projects/rbw)
    Updating crates.io index
   Compiling futures-core v0.3.31
   Compiling futures-sink v0.3.31
.
.
.
   Compiling axum v0.7.5
   Compiling rbw v1.12.1 (/home/adrian/projects/rbw)
error[E0658]: use of unstable library feature 'result_option_inspect'
    --> src/bin/rbw/commands.rs:1646:31
     |
1646 |     crate::actions::version().inspect_err(|_e| {
     |                               ^^^^^^^^^^^
     |
     = note: see issue #91345 <https://github.com/rust-lang/rust/issues/91345> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `rbw` (bin "rbw") due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rbw v1.12.1 (/home/adrian/projects/rbw)`, intermediate artifacts can be found at `/home/adrian/projects/rbw/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

I *can* compile the `main` branch, though.

**Comment by adrianschlatter** [comment]
Using rustc 1.83.0, PR #219 compiles and solves the issue for me.

**Comment by davla** [comment]
> Yup, I also ran into this problem. `rbw register` seems to work, `rbw login` fails with 429. I installed the official bw client on the same machine => no 429 problem. @davla: I'd offer to test #219, too, but I run into a problem. I'm a newby regarding rust/cargo so maybe I'm just doing an obvious mistake that you could help me correct? 🙏
> 
> ```
> git clone git@github.com:doy/rbw.git
> cd rbw
> git fetch origin pull/219/head:pr219
> git checkout pr219
> cargo install --locked -Znext-lockfile-bump --path .
> ```
> 
> I get
> 
> ```
> » cargo install --locked -Znext-lockfile-bump --path rbw
>   Installing rbw v1.12.1 (/home/adrian/projects/rbw)
>     Updating crates.io index
>    Compiling futures-core v0.3.31
>    Compiling futures-sink v0.3.31
> .
> .
> .
>    Compiling axum v0.7.5
>    Compiling rbw v1.12.1 (/home/adrian/projects/rbw)
> error[E0658]: use of unstable library feature 'result_option_inspect'
>     --> src/bin/rbw/commands.rs:1646:31
>      |
> 1646 |     crate::actions::version().inspect_err(|_e| {
>      |                               ^^^^^^^^^^^
>      |
>      = note: see issue #91345 <https://github.com/rust-lang/rust/issues/91345> for more information
> 
> For more information about this error, try `rustc --explain E0658`.
> error: could not compile `rbw` (bin "rbw") due to previous error
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `rbw v1.12.1 (/home/adrian/projects/rbw)`, intermediate artifacts can be found at `/home/adrian/projects/rbw/target`.
> To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
> ```
> 
> I _can_ compile the `main` branch, though.

Yeah, you need to compile with the latest version of the Rust compiler, because that's what is (righfully) used in this repository's Pull Requests checks. Specifically, the linter forced me to use that library feature that is apparently unstable in the Rust compiler version you used initially.

**Comment by doy** [comment]
sorry for the delay! this should be fixed in #219 and released in 1.13.0. let me know if there are still issues after upgrading!

**Comment by TGlide** [comment]
Thank you! @doy it seems it has not been updated in the Nix OS packages. Do you have to update it or? (new to Nix in general, so I'm a bit clueless)

**Comment by matthewarmand** [comment]
@TGlide According to Nix OS's package index (https://search.nixos.org/packages?channel=24.11&show=rbw&from=0&size=50&sort=relevance&type=packages&query=rbw) the `rbw` maintainers are

> Titouan Biteau <dev@geber.ga>
> Lucas Ransan <lucas@ransan.fr>

**Comment by sedlund** [comment]
this tracks the pull request for rbw 1.13.0 progression through the build system.

https://nixpkgs-tracker.ocfox.me/?pr=368532

now it is in nixos-unstable-small . so you can install it like this:

 > nix profile install --priority 4 github:nixos/nixpkgs/nixos-unstable-small#rbw

until it becomes available in whatever branch you are on - then remove this with:

> nix profile remove rbw

also, you should ask in nix related channels (https://matrix.to/#/#dev:nixos.org)
