### ISSUE TITLE
Cache credentials indefinitely 

### ISSUE THREAD

**Issue by apprehensions** [doy/rbw#222]
Within the Bitwarden browser extension, there is a feature where the vault timeout can be set to None, to essentially never ask the user for their credentials or a PIN if set.

It would be handy to see this feature being implemented, removing the need for `rbw-agent`.

**Comment by doy** [comment]
this should already be possible by setting the `lock_timeout` configuration value to a very high number - something like `rbw config set lock_timeout 999999999` should have the effect you're looking for.

**Comment by apprehensions** [comment]
I am already aware of this feature, which is why i used "indefinitely" and compared the feature to the bitwarden browser extension's feature. The extension can cache credentials indefinitely, forever, and never need to unlock. Where as setting the lock timeout to forever means it is forever for as long as the rbw daemon process is running for.

**Comment by Lockszmith-GH** [comment]
An old question, but you can use the regular bw and preserve the session key - those are indefinite.

**Comment by apprehensions** [comment]
Which is a feature of bw, which is why i created this feature request.
