### ISSUE TITLE
Failed to log in to bitwarden instance (2FA problem)

### ISSUE THREAD

**Issue by fedeizzo** [doy/rbw#23]
Hi, I've a problem during login.

Version:
`rbw --version
rbw 0.5.0`

Config file:
`{
"email":"my-email@myemail.com",
"base_url":null,
"identity_url":null,
"lock_timeout":3600
}`

Command:
`rbw login`

Error:
`rbw login: failed to log in to bitwarden instance: failed to parse JSON: TwoFactorProviders[0]: invalid type: string "0", expected u32 at line 1 column 93: invalid type: string "0", expected u32 at line 1 column 93`

I use [Authy](https://authy.com/) as 2FA provider

**Comment by djmbritt** [comment]
Hello there, 

I'm also having the same issue. It's not clear where I should be entering the 2FA in order to log in.

**Comment by Rayqan** [comment]
I am also facing the same issue. From the error message I think something changed on bitwarden's backend that messed with rbw's 2fa support.

**Comment by doy** [comment]
sorry about that! this should be fixed now in version 0.5.1.
