### ISSUE TITLE
rbw code doesn't accept otpauth urls

### ISSUE THREAD

**Issue by Tyilo** [doy/rbw#24]
My `TOTP Secret` field contains `otpauth://totp/Aarhus%20Universitet%3Aau522953%40uni.au.dk?secret=xxxxxxxxxxxxxxxx&issuer=Microsoft` and the bitwarden browser extension can correctly parse this and extract the secret.

It would be nice if rbw could do the same.

**Comment by doy** [comment]
fixed in e2b1070
