### ISSUE TITLE
Add space for user contributions

### ISSUE THREAD

**Issue by jedahan** [doy/rbw#29]
Either enabling the wiki or adding a `contrib/` directory where people could share their rbw integrations would be nice.

As an example, here is a little wrapper script I modified to work with rbw and such.

```bash
#!/bin/bash
# Wayland copy bitwarden passwords to paste once
set -eu

rbw unlocked || rbw unlock

set -o pipefail

wl-copy --paste-once "$(rbw-fzf)"
```

**Comment by doy** [comment]
i've been sticking these in `bin/` so far - happy to take pull requests for more of them

**Comment by jedahan** [comment]
pr created
