### ISSUE TITLE
Unable to get Items with Spaces in Name

### ISSUE THREAD

**Issue by schuppentier** [doy/rbw#33]
I have some Entries which have Spaces in their name, e.g. "Atlassian (Privat)". When I try to get that Entry by executing `rbw get "Atlassian (Privat)"`, rbw seems to ignore the Quotes and use the String as two arguments (Item Name and Folder) and yields the following result:
```
rbw get: couldn't find entry for '(Privat)@Atlassian': no entry found
```
My current workaround for those entries is to use the UUID but at the moment this does not work with the [Rofi script](https://github.com/fdw/rofi-rbw) I am using for accessing Bitwarden.

**Comment by doy** [comment]
i can't reproduce this - can you give me more information about how exactly you are running it?

**Comment by schuppentier** [comment]
I tried to add an entry via the command line and get the same behaviour:
![image](https://user-images.githubusercontent.com/1706418/104156906-547f1780-53ea-11eb-9f08-44a90b893036.png)

When I add the testentry via the app, I can see the entry after a sync but I am unable to get it via a get command:
![image](https://user-images.githubusercontent.com/1706418/104157047-a45dde80-53ea-11eb-90a8-fbf0cf566fe0.png)

Getting the entry via id works:
![image](https://user-images.githubusercontent.com/1706418/104157132-d40ce680-53ea-11eb-8284-6872cf4c4dcf.png)

I am using the latest release (0.5.2) from the [AUR](https://aur.archlinux.org/packages/rbw/) but I get the same errors with the Git version:
![image](https://user-images.githubusercontent.com/1706418/104157184-f0108800-53ea-11eb-8f4c-a8dac6fdb63d.png)

I usually use zsh, if that is relevant, but the errors remain the same in bash. Also, using the Linux TTY, the same error occurs, so it should not have anything to do with the Terminal emulator as well I think.

**Comment by xPMo** [comment]
What is the output of `which rbw`?

**Comment by schuppentier** [comment]
God, I am so dumb.
I have a `rbw` script in my PATH that checks if a Systemd Unit with the rbw agent is running and starts it if neccesary. I have done this, as mbsync sometimes did not correctly trigger the rbw password prompt.

This script was simply missing quotes. Thank you for the heads up @xPMo, finally everything works again. :)
