### ISSUE TITLE
[Feature Request] Output in raw/json format

### ISSUE THREAD

**Issue by xPMo** [doy/rbw#36]
I would like to use `jq` to manipulate my vault in the same way I did with the official bw client. So, I would like to see a `-j` `--json` option to `list` and `get`, to output in the same format `bw` does.

**Comment by mikeboiko** [comment]
agreed, this would be great!

**Comment by benedikt-bartscher** [comment]
I use qutebrowser and this would allow me to use rbw instead of bw for the qute-bitwarden userscript. I am currently using the official bw-cli, but its terrible slow

**Comment by alfonz19** [comment]
I'd like to ask for json support as well. That would be really useful when parsing output.

**Comment by alfonz19** [comment]
Thank you very much! Can't wait for new version with it so that I can get rid of ugly parsing! Thanks!
