### ISSUE TITLE
rbw-agent: Unable to disable PTRACE_ATTACH on this platform: not implemented

### ISSUE THREAD

**Issue by rjc** [doy/rbw#44]
Hello,

After installing the latest version with `cargo install rbw` on macOS 10.14, I get this:

    $ rbw --version
    rbw 1.1.0
    $ rbw login
    rbw-agent: Unable to disable PTRACE_ATTACH on this platform: not implemented. Agent memory may be dumpable by other processes.
    rbw login: failed to run rbw-agent: exit code: 1

Looks like a possible fall-out from #42.

**Comment by doy** [comment]
whoops, sorry, fixed!

**Comment by rjc** [comment]
@doy, no worries and thanks for the fix! :^)

Now, each time I run any command, I get:

    [2021-03-06T09:56:03Z WARN  rbw_agent] failed to disable PTRACE_ATTACH, agent memory may be dumpable by other processes: unimplemented on this platform

I'd rather not use `2>/dev/null` each time I run `rbw`, or create an alias or a script.

Any chance to get rid of the warning altogether on platforms which simply don't support it?

**Comment by doy** [comment]
oh, oops, the intention was for this to go to the agent logs rather than stdout. that should also be fixed now!

**Comment by rjc** [comment]
Thanks again for a quick fix!

I actually meant _getting rid of the warning altogether on platforms which don't support it_ quite literally as `rbw-agent` will be logging an error about missing functionalty which, currently, is Linux-specific. I'm simply wondering if there's much point in it. How about simply mentioning it in the `README` and be done with the warning? :^)
