### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by Frando** [doy/rbw#48]
Hi,
thanks for this tool. I have two instances of bitwarden (through [bitwarden-rs](https://github.com/dani-garcia/bitwarden_rs)) that I use frequently (personal and work). Is there a way to switch between accounts in rbw? Maybe like running two agents and passing an environment variable or option to rbw to chose the right one?

**Comment by doy** [comment]
you can switch between two different instances with `rbw config`, but running multiple agents isn't currently supported (so you'd have to re-enter your password each time you switch). this would be a useful feature, though!

**Comment by ptman** [comment]
#28
