### ISSUE TITLE
`rbw gen` - password length not respected and differs depending on options used

### ISSUE THREAD

**Issue by rjc** [doy/rbw#54]
Hello,

I just noticed that the length of a generated password is not respected and is limited depending on what option has been used, i.e.:

- **94** without any options
- **62** with `--no-symbols`
- **24** with `--nonconfusables`
- **10** with `--only-numbers`

[Attached](https://github.com/doy/rbw/files/6326231/rbw-gen.txt) is an output of:

    for i in $(jot 100)
    do
            echo $i characters
            rbw gen $i | wc -m
            rbw gen $i --no-symbols | wc -m
            rbw gen $i --nonconfusables | wc -m
            rbw gen $i --only-numbers | wc -m
    done > rbw-pass

_GNU coreutils_ users will need to replace `jot(1)` with `seq(1)`. The results are _off by one_ due to newline character being present and counted.

Also, while we're at it, options are doubled on error, i.e.:

    $ rbw gen --only-numbers
    error: The following required arguments were not provided:
        <len>

    USAGE:
        rbw generate <len> <--no-symbols|--only-numbers|--nonconfusables|--diceware|--no-symbols|--only-numbers|--nonconfusables|--diceware>

    For more information try --help

**Comment by doy** [comment]
fixed in c248016, thanks!

**Comment by doy** [comment]
(the second issue is https://github.com/clap-rs/clap/issues/1487 which will hopefully be resolved once clap 3 is eventually released)
