### ISSUE TITLE
Is there currently a way to handle entries which have the same name ?

### ISSUE THREAD

**Issue by pyrr** [doy/rbw#6]
>rbw get: couldn't find entry for 'Google': multiple entries found

I don't mind making the names unique, just asking.

**Comment by doy** [comment]
you can pass a second argument to `rbw get` to match on the username, like `rbw get google pyrr` - does this help?

**Comment by pyrr** [comment]
Yep that works. Thanks.

**Comment by AdmiralNemo** [comment]
Item name and username are not unique enough for me, unfortunately.  I have several items with the same name and username (e.g. root password for various machines), stored in different folder.  Could we get a way to either refer to items by UUID, like `bw` does, or folder+name?

**Comment by doy** [comment]
@AdmiralNemo: `rbw` already supports referring to items by uuid (this is maybe not clear from the docs, sorry!). additionally, in 0.4.4 i added a `--folder` option to `rbw get` to let you explicitly choose the folder as well. let me know if you need anything else!

**Comment by mhellwig** [comment]
I am not sure if I am using it wrong, but similarly to the above, there doesn't seem to be a way to address entries if there are multiple entries with the same name from different collections (rather than folders).
Am I correct in assuming that currently, rbw doesn't do collections?
