### ISSUE TITLE
Failed to login, missing field `Kdf`

### ISSUE THREAD

**Issue by Congee** [doy/rbw#80]
I am using version 1.4.1 and unable to login with the following error. I guess the upstream API has changed?
> rbw login: failed to log in to bitwarden instance: failed to parse JSON: .: missing field `Kdf` at line 1 column 32: missing field `Kdf` at line 1 column 32

**Comment by carlosala** [comment]
Same issue here!

**Comment by nanounanue** [comment]
I can confirm this. Same error.

**Comment by doy** [comment]
this should be fixed in eb13ab2 - i'll get a release out soon

**Comment by doy** [comment]
fixed in 1.4.2

**Comment by carlosala** [comment]
thanks @doy, you're the best!🔥
