### ISSUE TITLE
Feature request: instead of adding another agent, use a predefined gpg-agent

### ISSUE THREAD

**Issue by nicolas-graves** [doy/rbw#84]
Hi ! Thanks again for this amazing piece of software. 
In the last year, I find myself occasionnally switching between pass and rbw. 
What I used to like on Arch was in particular the possibility to automatically log into my GPG key on login with [pam-gnupg](https://github.com/cruegge/pam-gnupg) so I never needed to input my password once logged onto my system. 
Now on guix + wayland, I often have issues because of pinentry, and feel that if there was the option to use an already activated gpg-agent to use the database, it could enable some nice customizations (because of the already rich ecosystem and tools around gnupg). 
I haven't delved in the source code at all for now, and probably don't have time to do it in the next month, but might try to implement such a thing, but I had a question regarding such a feature before even considering that : 
- does it seem possible to add that as a simple option (in the config file or as a flag) ? or would it rather need a major rewrite ? or even considering writing another program, maybe with some parts of rbw ?

**Comment by doy** [comment]
this would be a pretty significant rewrite, and i'm not entirely sure if it would even be possible (i don't know much about how the gpg agent works, but rbw-agent handles all of the decryption, not just key storage). i think it would likely be less effort to write a separate `pam-rbw` module, or something along those lines.
