### ISSUE TITLE
`rbw get` shouldn't output a newline when piping

### ISSUE THREAD

**Issue by Witcher01** [doy/rbw#85]
Calling `rbw get` also outputs a newline when piped into another program like `xclip`.

In my opinion this should be avoided to allow nice integration into a shell script, for instance, without having to strip newlines.

Should this be implemented?

**Comment by ambroisie** [comment]
This could even be gated behing a call to `isatty` to check if it is used to show the password interactively or as part of a pipeline.

And of course, a command line argument to explicitly get either behaviour.

**Comment by doy** [comment]
#120 should resolve this.
