### ISSUE TITLE
failed to parse pinentry output (Timeout)

### ISSUE THREAD

**Issue by AdmiralNemo** [doy/rbw#9]
If the user does not respond to the PIN entry prompt within the timeout (default 60 seconds), `rbw` prints the following:

````
failed to parse pinentry output ("S ERROR gtk2.? 83886142 \nERR 83886142 Timeout <Pinentry>\n\u{0}…
````

The `\u{0}` sequence then repeats 4038 more times.

This happens for both `pinentry-gtk` and `pinentry-curses`.

**Comment by doy** [comment]
this should be fixed in b1600a80d26e, thanks!
