### ISSUE TITLE
rotate encrytion key

### ISSUE THREAD

**Issue by umop3plsdn** [doy/rbw#96]
I keep getting: rbw list: failed to unlock database: cipherstring type 0 too old
Please rotate your account encryption key (https://bitwarden.com/help/article/account-encryption-key/) and try again.

I know how to rotate the encryption key and i've literally tried 10 different times with 10 different passwords. It's the checkbox you check when you change the master password. I've tried from 2 different web browsers and my phone to make sure that maybe it was a web browser problem. I've deleted the config.json file in between as well to enjure a fresh start. can anyone think of anything else it could be?

**Comment by umop3plsdn** [comment]
I thought maybe it had something to do with the API key so I changed it bitwarden now. It wont let me register with a new API key though even if I delete the config. I tried using rbw config unset but I don't know the old key to remove now LOL

**Comment by umop3plsdn** [comment]
if anyone else has this issue all i did was a purge and then typed list again and it worked perfectly

**Comment by JokerQyou** [comment]
This is actually not a bug. For users used Bitwarden or Vaultwarden before version `2023.2.0`, your account might be using a KDF iteration number that's considered too low (and insecure) in current versions of Bitwarden, see [Low KDF iterations](https://bitwarden.com/help/kdf-algorithms/#low-kdf-iterations). The solution is to either change KDF algorithm to Argon2id with default parameters, or increase iteration number of PBKDF2 to at leaset 600,000. After that, be sure to rotate your encryption key to re-encrypt your vault data, follow [this guide](https://bitwarden.com/help/account-encryption-key/).
