### ISSUE TITLE
Cannot source auto completion script for zsh 

### ISSUE THREAD

**Issue by jaypikay** [doy/rbw#98]
To test the auto completion I have tried to source the output of _gen-completions_, but get an error message which breaks the initialization.

```sh
$ source <(rbw gen-completions zsh)
_arguments:comparguments:327: can only be called from completion function
```

Not sure if I am using it wrong, or if there is a problem with the generated script.

**Comment by ealvar3z** [comment]
Did you generate the completion script during compilation? *a la* this:

`cargo run --release --locked --bin rbw -- gen-completions zsh >zsh-completions`

**Comment by jaypikay** [comment]
I have installed it through the *Community* repository in Arch Linux. The PGKBUILD is doing it the way you described:

```
  # generate shell auto-completions
  for completion in bash fish zsh; do
    cargo run --frozen --release --bin rbw -- \
      gen-completions "$completion" > "$completion-completions"
  done
```

**Comment by benedikt-bartscher** [comment]
See https://github.com/ahmetb/kubectx/issues/285

**Comment by doy** [comment]
yeah, the intended way to use this is to put the generated script on your `fpath`. i'm not sure what just sourcing the output directly would do, but it's not something intended to be supported.
